"""make wallet_id nullable in transactions

Revision ID: 3191d21a7650
Revises: c514179d87d7
Create Date: 2026-02-19 14:55:12.936330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3191d21a7650'
down_revision: Union[str, None] = 'c514179d87d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'wallet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'wallet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
