"""remove wallet_id from transactions

Revision ID: 75347140f394
Revises: 3191d21a7650
Create Date: 2026-02-19 14:57:00.463887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '75347140f394'
down_revision: Union[str, None] = '3191d21a7650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_ibfk_3', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'wallet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('wallet_id', mysql.INTEGER(display_width=11), nullable=True))
    op.create_foreign_key('transactions_ibfk_3', 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###
